config/accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

favorites_url = [
    path('', views.UserFavoritesView.as_view(), name='user_favorites'),
    path('add/<int:pk>/', views.AddFavoritesView.as_view(), name='add_favorites'),
    path('remove/<int:pk>/', views.RemoveFavoritesView.as_view(), name='remove_favorites')
]

profile_url = [
    path('info/', views.EditUserInfoView.as_view(), name='user_info_edit'),
    path('password/', views.UpdatePassword.as_view(), name='user_password_edit')
]

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('forgot/', views.UserPasswordResetView.as_view(), name='forgot_password'),
    path('forgot/verify/', views.UserPasswordResetVerifyCodeView.as_view(), name='forgot_password_verify'),

    path('edit/', include(profile_url)),
    path('favorites/', include(favorites_url)),
]

config/blog/urls.py
from django.urls import path

from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/<slug:slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('book/', include('book.urls', namespace='book')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('order/', include('order.urls', namespace='order'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/home/urls.py
from django.urls import path

from . import views


app_name = "home"
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('about/', views.about_view, name="about"),
    path('contact/', views.contacts_view, name="contact"),
    path('faq/', views.faq_view, name="faq"),
    path('privacy/', views.privacy_view, name="privacy"),
]

config/order/urls.py
from django.urls import path, include
from . import views

app_name = 'order'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name="user_profile"),
    path('premiums/', views.PremiumPlansView.as_view(), name="premium_plans"),
    path('create/<int:plan_id>/', views.OrderCreateView.as_view(), name="create_order"),
    path('pay/<int:order_id>/', views.ZPOrderPayView.as_view(), name="pay_order"),
    path('verify/', views.OrderVerifyView.as_view(), name="verify_order")
]

config/order/models.py
from django.db import models
from django.contrib.auth import get_user_model
from ckeditor.fields import RichTextField
from django.core.validators import MinValueValidator, MaxValueValidator


class PremiumPlan(models.Model):
    name = models.CharField(max_length=200)
    description = RichTextField()
    price = models.IntegerField()

    longtime = models.DurationField()

    class Meta:
        ordering = ('-price', )

    def __str__(self):
        return self.name

    @property
    def months_duration(self):
        # Calculate the number of months based on the duration in the 'longtime' field
        if self.longtime:
            # Calculate the total number of days in the duration
            total_days = self.longtime.days
            # Calculate the number of months (assuming 30 days per month)
            total_months = total_days // 30
            total_year = total_months//12

            if total_year >= 1:
                return "%s سال" % total_year
            return "%s ماه" % total_months
        else:
            return 0


class PremiumOrder(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='premium_orders')
    plan = models.ForeignKey('PremiumPlan', on_delete=models.SET_NULL, null=True)

    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)

    paid = models.BooleanField(default=False)
    paid_count = models.IntegerField()
    tracking_code = models.CharField(max_length=250, null=True, blank=True)

    class Meta:
        ordering = ('paid', '-datetime_modified')

    def __str__(self):
        return f'{self.user} - {str(self.id)}'


class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(90)])
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.code

config/order/forms.py
from django import forms


class CouponApplyForm(forms.Form):
    code = forms.CharField(
        label="کد تخفیف",
        widget=forms.TextInput(attrs={"class": "sign__input", "placeholder": 'XXXX'})
    )

    def clean_code(self):
        cd = self.cleaned_data
        if cd['code']:
            try:
                coupon = Coupon.objects.get(code__exact=code, valid_from__lte=now, valid_to__gte=now, active=True)
                return coupon.discount
            except Coupon.DoesNotExist:
                raise ValueError("این کد تخفیف وجود ندارد!")
        return 0

config/order/views.py
from config.settings import MERCHANT, ZP_Description, CallbackURL
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View, generic
from django.core.paginator import Paginator
from django.contrib import messages
from django.http import HttpResponse

import datetime
import requests
import json

from .models import PremiumOrder, PremiumPlan

ZP_API_REQUEST = "https://api.zarinpal.com/pg/v4/payment/request.json"
ZP_API_VERIFY = "https://api.zarinpal.com/pg/v4/payment/verify.json"
ZP_API_STARTPAY = "https://www.zarinpal.com/pg/StartPay/{authority}"


class ProfileView(LoginRequiredMixin, View):
    template_name = 'order/profile.html'

    def setup(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            orders = PremiumOrder.objects.filter(user=request.user)
            paginator = Paginator(orders, 25)
            page_number = request.GET.get("page")
            self.page_obj = paginator.get_page(page_number)
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {"orders": self.page_obj})


class PremiumPlansView(LoginRequiredMixin, generic.ListView):
    template_name = 'order/premium_plan_list.html'
    model = PremiumPlan


class OrderCreateView(LoginRequiredMixin, View):

    def setup(self, request, *args, **kwargs):
        self.plan = get_object_or_404(PremiumPlan, pk=kwargs['plan_id'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, 'order/accept_order.html', {'plan': self.plan})

    def post(self, request, *args, **kwargs):
        price = self.plan.price
        order = PremiumOrder.objects.create(
            user=request.user,
            plan=self.plan,
            paid_count=price
        )
        order.save()
        request.session['order_pay'] = {
            'order_id': order.id,
        }
        messages.success(request, 'در حال انتفال به صفحه پرداخت هستید', 'success')
        return redirect(reverse('order:pay_order', args=(order.pk,)))


class ZPOrderPayView(LoginRequiredMixin, View):
    def get(self, request, order_id):
        order = get_object_or_404(PremiumOrder, pk=order_id)

        req_data = {
            "merchant_id": MERCHANT,
            "amount": order.paid_count,
            "callback_url": CallbackURL,
            "description": ZP_Description,
            "metadata": {"mobile": request.user.phone_number, "email": request.user.email}
        }
        req_header = {"accept": "application/json", "content-type": "application/json'"}
        req = requests.post(
            url=ZP_API_REQUEST,
            data=json.dumps(req_data),
            headers=req_header
        )
        if len(req.json()['errors']) == 0:
            return redirect(ZP_API_STARTPAY.format(authority=req.json()['data']['authority']))
        else:
            e_code = req.json()['errors']['code']
            e_message = req.json()['errors']['message']
            messages.error(
                request,
                "مشکلی در انتقال به شبکه پرداخت به وجود آمده است لطفا دقایقی دیگر دوباره امتحان نمایید!",
                "danger"
            )
            order.delete()
            request.session['order_pay'] = {}
            # return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")
            return redirect(reverse("order:premium_plans"))


class OrderVerifyView(LoginRequiredMixin, View):
    def get(self, request):
        order_id = request.session['order_pay']['order_id']
        order = get_object_or_404(PremiumOrder, pk=order_id)
        t_status = request.GET.get('Status')
        t_authority = request.GET['Authority']
        if request.GET.get('Status') == 'OK':
            req_header = {"accept": "application/json", "content-type": "application/json'"}
            req_data = {
                "merchant_id": MERCHANT,
                "amount": order.paid_count,
                "authority": t_authority
            }
            req = requests.post(url=ZP_API_VERIFY, data=json.dumps(req_data), headers=req_header)
            if len(req.json()['errors']) == 0:
                t_status = req.json()['data']['code']
                if t_status == 100:
                    order.paid = True
                    order.tracking_code = str(req.json()['data']['ref_id'])
                    order.save()
                    user = request.user
                    user.premium_expire_date = datetime.datetime.now() + order.plan.longtime
                    user.save()
                    # return HttpResponse('Transaction success.\nRefID: ' + str(req.json()['data']['ref_id']))
                    messages.success(request, "پرداخت موفقیت آمیز بود %s" % str(req.json()['data']['ref_id']))
                elif t_status == 101:
                    # return HttpResponse('Transaction submitted : ' + str(req.json()['data']['message']))
                    messages.success(request, "تراکنش ارسال شده %s" % str(req.json()['data']['message']))
                else:
                    # return HttpResponse('Transaction failed.\nStatus: ' + str(req.json()['data']['message']))
                    messages.error(request, "Transaction failed.\nStatus: " + str(req.json()['data']['message']),
                                   "danger")
            else:
                e_code = req.json()['errors']['code']
                e_message = req.json()['errors']['message']
                messages.error(request, f"Error code: {e_code}, Error Message: {e_message}", "danger")
                # return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")
        else:
            # return HttpResponse('Transaction failed or canceled by user')
            messages.error(request, "Transaction failed or canceled by user", "danger")
        return redirect(reverse('order:user_profile'))

config/order/templates/order/accept_order.html
{% extends 'accounts/_base.html' %}
{% load humanize %}
{% load order_tags %}

{% block title_content %}
    تایید خرید
{% endblock %}

{% block content %}
    <form class="loginfrm">
        <h1 class="details__title" dir="auto">
            <b>
            پلن {{ plan }}
            </b>
        </h1>
    </form>
    <br>
    <form class="loginfrm" method="post" action="">
        {% csrf_token %}
        <h4 class="details__title">((پرداخت با زرین‌پال))</h4>
        <span class="details__cart-title">قیمت</span>
        <div class="details__price">
            <span>{{ plan.price | intcomma }} تومن</span>
            <s>{{ plan.price | intcomma }}</s><b>0% تخفیف</b>
        </div>
        <input class="sign__btn" type="submit" value="رفتن به درگاه پرداخت" disabled>
    </form>
    <br>
    <form class="loginfrm">
        <h4 class="details__title">((پرداخت با کارت به کارت))</h4>
        <h5 class="details__cart-title" dir="auto">telegram-id: @yasin_dev81</h5>
        <span class="details__cart-title">قیمت</span>
        <div class="details__price">
            <span>{{ plan.price | discount_kart | intcomma }} تومن</span>
            <s>{{ plan.price | intcomma }}</s><b>25% تخفیف</b>
        </div>
        <a class="sign__btn footer__link" type="submit" href="tel:@yasin_dev81"> رفتن به تلگرام </a>
        <div class="row justify-content-center text-center">
            <a href="{% url 'order:premium_plans' %}" class="btn btn-outline-danger"> بازگشت </a>
        </div>
    </form>
{% endblock %}

config/order/templates/order/checkout.html
{% extends '_base.html' %}
{% load static %}
{% load humanize %}

{% block title_content %}
    پلن‌های اشتراک ویژه
{% endblock %}

{% block style_content %}
    <style>

        .card1:hover {
            background: #00C9FF;
            border: 1px solid #00C9FF;
        }

        .card1:hover .list-group-item {
            background: #00C9FF !important
        }

        .card1 {
            background: whitesmoke;
        }
    </style>
{% endblock %}

{% block content %}
    <!-- page title -->
    <section class="section section--first section--last section--head" data-bg="{% static 'img/bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section__wrap">
                        <!-- section title -->
                        <h2 class="section__title">
                            پلن‌های اشتراک ویژه
                        </h2>
                        <!-- end section title -->

                        <!-- breadcrumb -->
                        <ul class="breadcrumb">
                            <li class="breadcrumb__item"><a href="{% url 'home:home' %}">خانه</a></li>
                            <li class="breadcrumb__item breadcrumb__item--active">پروفایل</li>
                        </ul>
                        <!-- end breadcrumb -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end page title -->

    <div class="container-fluid">
        <div class="container p-5">
            <div class="row d-flex justify-content-center">
                {% for plan in premiumplan_list %}
                    <div class="col-lg-4 col-md-12 mb-4">
                        <div class="card card1 h-100">
                            <div class="card-body">

                                <h3 class="card-title">{{ plan.name }}</h3>
                                <small class='text-muted'>{{ plan.months_duration }}</small>
                                <br><br><br>
                                <span class="h2">{{ plan.price | intcomma }} تومن</span>/{{ plan.months_duration }}
                                <br><br>
                                <a class="d-grid my-3" href="{% url 'order:create_order' plan.pk %}">
                                    <button class="btn btn-outline-dark btn-block">انتخاب</button>
                                </a>
                                <ul>
                                    {{ plan.description | safe }}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

config/order/templates/order/premium_plan_list.html
{% extends '_base.html' %}
{% load static %}
{% load humanize %}

{% block title_content %}
    پلن‌های اشتراک ویژه
{% endblock %}

{% block style_content %}
    <style>

        .card1:hover {
            background: white;
            border: 1px solid white;
        }

        .card1:hover .list-group-item {
            background: white !important
        }

        .card1 {
            background: #00C9FF;
        }
    </style>
{% endblock %}

{% block content %}
    <!-- page title -->
    <section class="section section--first section--last section--head" data-bg="{% static 'img/bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section__wrap">
                        <!-- section title -->
                        <h2 class="section__title">
                            پلن‌های اشتراک ویژه
                        </h2>
                        <!-- end section title -->

                        <!-- breadcrumb -->
                        <ul class="breadcrumb">
                            <li class="breadcrumb__item"><a href="{% url 'home:home' %}">خانه</a></li>
                            <li class="breadcrumb__item breadcrumb__item--active">پروفایل</li>
                        </ul>
                        <!-- end breadcrumb -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end page title -->

    <div class="container-fluid">
        <div class="container p-5">
            <div class="row d-flex justify-content-center">
                {% for plan in premiumplan_list %}
                    <div class="col-lg-4 col-md-12 mb-4">
                        <div class="card card1 h-100">
                            <div class="card-body">

                                <h3 class="card-title">{{ plan.name }}</h3>
                                <small class='text-muted'>{{ plan.months_duration }}</small>
                                <br><br><br>
                                <span class="h2">{{ plan.price | intcomma }} تومن</span>/{{ plan.months_duration }}
                                <br><br>
                                <a class="d-grid my-3" href="{% url 'order:create_order' plan.pk %}">
                                    <button class="btn btn-outline-dark btn-block">انتخاب</button>
                                </a>
                                <ul>
                                    {{ plan.description | safe }}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

config/order/templates/order/profile.html
{% extends '_base.html' %}
{% load static %}
{% load humanize %}

{% block title_content %}
    پروفایل
{% endblock %}

{% block content %}
    <!-- page title -->
    <section class="section section--first section--last section--head" data-bg="{% static 'img/bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section__wrap">
                        <!-- section title -->
                        <h2 class="section__title">پروفایل</h2>
                        <!-- end section title -->

                        <!-- breadcrumb -->
                        <ul class="breadcrumb">
                            <li class="breadcrumb__item"><a href="{% url 'home:home' %}">خانه</a></li>
                            <li class="breadcrumb__item breadcrumb__item--active">پروفایل</li>
                        </ul>
                        <!-- end breadcrumb -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end page title -->

    <!-- section -->
    <section class="section section--last">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="profile">
                        <ul class="nav nav-tabs profile__tabs" id="profile__tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#tab-1" role="tab"
                                   aria-controls="tab-1" aria-selected="true">تراکنش‌های من</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#tab-2" role="tab" aria-controls="tab-2"
                                   aria-selected="false">تنظیمات</a>
                            </li>
                        </ul>

                        <a class="profile__logout" type="button" href="{% url 'accounts:user_logout' %}">خروج</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <!-- content tabs -->
            <div class="tab-content">
                <div class="tab-pane fade show active" id="tab-1" role="tabpanel">
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive table-responsive--border">
                                <table class="profile__table">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>کد رهگیری</th>
                                        <th>عنوان (نوع پلن)</th>
                                        <th>تاریخ</th>
                                        <th>قیمت</th>
                                        <th>وضعیت</th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    {% for order in orders %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td><a href="#">{{ order.tracking_code }}</a></td>
                                            <td>{{ order.plan.name }}</td>
                                            <td>{{ order.datetime_modified }}</td>
                                            <td><span class="profile__price">{{ order.paid_count | intcomma }}</span>
                                            </td>
                                            {% if order.paid %}
                                                <td><span
                                                        class="profile__status profile__status--confirmed">پرداخت شده</span>
                                                </td>
                                            {% else %}
                                                <td><span
                                                        class="profile__status profile__status--cenceled">پرداخت نشده</span>
                                                </td>
                                            {% endif %}
                                        </tr>
                                        <tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <!-- paginator -->
                        <div class="col-12">
                            <div class="paginator">
                                <div class="paginator__counter">
                                    صفحه {{ orders.number }} از {{ orders.paginator.num_pages }}
                                </div>

                                <ul class="paginator__wrap">
                                    {% if orders.has_previous %}
                                        <li class="paginator__item paginator__item--prev">
                                            <a href="?page={{ orders.previous_page_number }}">
                                                <svg xmlns='http://www.w3.org/2000/svg' width='512' height='512'
                                                     viewBox='0 0 512 512'>
                                                    <polyline points='268 112 412 256 268 400'
                                                              style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:48px'/>
                                                    <line x1='392' y1='256' x2='100' y2='256'
                                                          style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:48px'/>
                                                </svg>
                                            </a>
                                        </li>
                                        <li class="paginator__item"><a
                                                href="?page={{ orders.previous_page_number }}">{{ orders.previous_page_number }}</a>
                                        </li>
                                    {% endif %}
                                    <li class="paginator__item paginator__item--active"><a
                                            href="#">{{ orders.number }}</a></li>

                                    {% if orders.has_next %}
                                        <li class="paginator__item"><a
                                                href="?page={{ orders.next_page_number }}">{{ orders.next_page_number }}</a>
                                        </li>
                                        <li class="paginator__item paginator__item--next">
                                            <a href="?page={{ orders.next_page_number }}">
                                                <svg xmlns='http://www.w3.org/2000/svg' width='512' height='512'
                                                     viewBox='0 0 512 512'>
                                                    <polyline points='244 400 100 256 244 112'
                                                              style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:48px'/>
                                                    <line x1='120' y1='256' x2='412' y2='256'
                                                          style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:48px'/>
                                                </svg>
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                        <!-- end paginator -->
                    </div>
                </div>

                <div class="tab-pane fade" id="tab-2" role="tabpanel">
                    <div class="row">
                        <!-- details form -->
                        <div class="col-12 col-lg-6">
                            <form action="#" class="form">
                                <div class="row">
                                    <div class="col-12">
                                        <h4 class="form__title">جزئیات پروفایل</h4>
                                    </div>

                                    <div class="col-12 col-md-6 col-lg-12 col-xl-6">
                                        <p class="form__label">نام و نام خانوادگی :</p>
                                        <p class="text-center text-light">{{ user.full_name }}</p>
                                    </div>

                                    <div class="col-12 col-md-6 col-lg-12 col-xl-6">
                                        <p class="form__label">شماره تلفن :</p>
                                        <p class="text-center text-light">{{ user.phone_number }}</p>
                                    </div>

                                    <div class="col-12 col-md-6 col-lg-12 col-xl-6">
                                        <p class="form__label">ایمیل :</p>
                                        <p class="text-center text-light">{{ user.email }}</p>
                                    </div>

                                    <div class="col-12 col-md-6 col-lg-12 col-xl-6">
                                        <p class="form__label">پریمیوم :</p>
                                        {% if user.is_premium %}
                                            <p class="text-center text-light">
                                                فعال است
                                            </p>
                                        {% else %}
                                            <div class="text-center text-danger">
                                                غیرفعال است
                                            </div>
                                        {% endif %}
                                    </div>
                                    {% if user.premium_expire_date %}
                                        <div class="col-12 col-md-6 col-lg-12 col-xl-6">
                                            <p class="form__label">تاریخ اتمام پلن پریمیوم :</p>
                                            <p class="text-center text-light">{{ user.premium_expire_date }}</p>
                                        </div>
                                    {% endif %}

                                    <p></p>

                                    <div class="col-12">
                                        <a class="form__btn" type="button" href="{% url 'accounts:user_info_edit' %}">رفتن
                                            به صفحه تغییر</a>
                                    </div>
                                    <br>
                                </div>
                            </form>
                        </div>
                        <!-- end details form -->
                    </div>
                </div>
            </div>
            <!-- end content tabs -->
        </div>
    </section>
    <!-- end section -->
{% endblock %}