config/accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

favorites_url = [
    path('', views.UserFavoritesView.as_view(), name='user_favorites'),
    path('add/<int:pk>/', views.AddFavoritesView.as_view(), name='add_favorites'),
    path('remove/<int:pk>/', views.RemoveFavoritesView.as_view(), name='remove_favorites')
]

profile_url = [
    path('info/', views.EditUserInfoView.as_view(), name='user_info_edit'),
    path('password/', views.UpdatePassword.as_view(), name='user_password_edit')
]

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('forgot/', views.UserPasswordResetView.as_view(), name='forgot_password'),
    path('forgot/verify/', views.UserPasswordResetVerifyCodeView.as_view(), name='forgot_password_verify'),

    path('edit/', include(profile_url)),
    path('favorites/', include(favorites_url)),
]

config/blog/urls.py
from django.urls import path

from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/<slug:slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
]

config/book/urls.py
from django.urls import path, include
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.BookListView.as_view(), name="book_list"),
    path('book/<int:pk>/<slug:slug>/', views.BookDetailView.as_view(), name="book_detail")
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('book/', include('book.urls', namespace='book')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('order/', include('order.urls', namespace='order'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/home/urls.py
from django.urls import path

from . import views


app_name = "home"
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('about/', views.about_view, name="about"),
    path('contact/', views.contacts_view, name="contact"),
    path('faq/', views.faq_view, name="faq"),
    path('privacy/', views.privacy_view, name="privacy"),
]

config/order/urls.py
from django.urls import path, include
from . import views

app_name = 'order'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name="user_profile"),
    path('premiums/', views.PremiumPlansView.as_view(), name="premium_plans"),
    path('create/<int:plan_id>/', views.OrderCreateView.as_view(), name="create_order"),
    path('pay/<int:order_id>/', views.ZPOrderPayView.as_view(), name="pay_order"),
    path('verify/', views.OrderVerifyView.as_view(), name="verify_order")
]

config/home/models.py
from django.db import models

# Create your models here.

config/home/views.py
from django.shortcuts import render
from django.views import View

from book.models import Book
from blog.models import Blog


class HomeView(View):
    template_name = 'home/home.html'
    counte_each = 4

    def setup(self, request, *args, **kwargs):
        self.best_books = sorted(Book.objects.all(), key=lambda t: int(t.like_count)*(-1))[:self.counte_each]
        self.last_books = Book.objects.all().order_by('-datetime_created')[:self.counte_each*2]
        self.last_blogs = Blog.objects.all()[:2]
        self.blogs = Blog.objects.all().order_by('?')[:3]
        return super().setup(request, *args, **kwargs)

    def get(self, request):
        return render(
            request,
            self.template_name,
            context={
                'best_book': self.best_books,
                'last_book': self.last_books,
                'last_blogs': self.last_blogs,
                'blogs': self.blogs
            }
        )


def about_view(request):
    last_books = Book.objects.all().order_by('-datetime_created')[:10]
    return render(request, 'home/about.html', {'last_book': last_books})


def contacts_view(request):
    last_books = Book.objects.all().order_by('-datetime_created')[:10]
    return render(request, 'home/contacts.html', {'last_book': last_books})


def faq_view(request):
    last_books = Book.objects.all().order_by('-datetime_created')[:10]
    return render(request, 'home/faq.html', {'last_book': last_books})


def privacy_view(request):
    last_books = Book.objects.all().order_by('-datetime_created')[:10]
    return render(request, 'home/privacy.html', {'last_book': last_books})

config/home/templates/home/contacts.html
{% extends '_base.html' %}
{% load static %}

{% block title_content %}
    تماس با ما
{% endblock %}

{% block content %}
<!-- page title -->
<section class="section section--first section--last section--head" data-bg="{% static 'img/bg.jpg' %}">
    <div class="container">
    <div class="row">
        <div class="col-12">
        <div class="section__wrap">
            <!-- section title -->
            <h2 class="section__title">تماس با ما</h2>
            <!-- end section title -->

            <!-- breadcrumb -->
            <ul class="breadcrumb">
            <li class="breadcrumb__item"><a href="{% url 'home:home' %}">خانه</a></li>
            <li class="breadcrumb__item breadcrumb__item--active">تماس با ما</li>
            </ul>
            <!-- end breadcrumb -->
        </div>
        </div>
    </div>
    </div>
</section>
<!-- end page title -->

<!-- section -->
<section class="section">
    <div class="container">
    <div class="row">
{#        <div class="col-12 col-md-7 col-xl-8">#}
{#        <div class="row">#}
{#            <!-- section title -->#}
{#            <div class="col-12">#}
{#            <h2 class="section__title">فرم تماس</h2>#}
{#            </div>#}
{#            <!-- end section title -->#}
{##}
{#            <div class="col-12">#}
{#            <form action="#" class="form form--contacts">#}
{#                <input type="text" class="form__input" placeholder="نام و نام خانوادگی">#}
{#                <input type="text" class="form__input" placeholder="ایمیل">#}
{#                <input type="text" class="form__input" placeholder="موضوع">#}
{#                <textarea name="text" class="form__textarea" placeholder="پیام خود را بنویسید"></textarea>#}
{#                <button type="button" class="form__btn">ارسال</button>#}
{#            </form>#}
{#            </div>#}
{#        </div>#}
{#        </div>#}

        <div class="col-12 col-md-5 col-xl-4">
        <div class="row">
            <!-- section title -->
            <div class="col-12">
            <h2 class="section__title">اطلاعات</h2>
            </div>
            <!-- end section title -->

            <div class="col-12">
            <p class="section__text section__text--mt">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.</p>

            <ul class="contacts__list">
                <li><a href="tel:#">+98 (21) 22-33-44-55</a></li>
                <li><a href="mailto:#">support@filmaro.template</a></li>
            </ul>
            <div class="contacts__social">
                <a class="fb" href="#"><svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><path d='M455.27,32H56.73A24.74,24.74,0,0,0,32,56.73V455.27A24.74,24.74,0,0,0,56.73,480H256V304H202.45V240H256V189c0-57.86,40.13-89.36,91.82-89.36,24.73,0,51.33,1.86,57.51,2.68v60.43H364.15c-28.12,0-33.48,13.3-33.48,32.9V240h67l-8.75,64H330.67V480h124.6A24.74,24.74,0,0,0,480,455.27V56.73A24.74,24.74,0,0,0,455.27,32Z'/></svg></a>
                <a class="inst" href="#"><svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><path d='M349.33,69.33a93.62,93.62,0,0,1,93.34,93.34V349.33a93.62,93.62,0,0,1-93.34,93.34H162.67a93.62,93.62,0,0,1-93.34-93.34V162.67a93.62,93.62,0,0,1,93.34-93.34H349.33m0-37.33H162.67C90.8,32,32,90.8,32,162.67V349.33C32,421.2,90.8,480,162.67,480H349.33C421.2,480,480,421.2,480,349.33V162.67C480,90.8,421.2,32,349.33,32Z'/><path d='M377.33,162.67a28,28,0,1,1,28-28A27.94,27.94,0,0,1,377.33,162.67Z'/><path d='M256,181.33A74.67,74.67,0,1,1,181.33,256,74.75,74.75,0,0,1,256,181.33M256,144A112,112,0,1,0,368,256,112,112,0,0,0,256,144Z'/></svg></a>
                <a class="tw" href="#"><svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><path d='M496,109.5a201.8,201.8,0,0,1-56.55,15.3,97.51,97.51,0,0,0,43.33-53.6,197.74,197.74,0,0,1-62.56,23.5A99.14,99.14,0,0,0,348.31,64c-54.42,0-98.46,43.4-98.46,96.9a93.21,93.21,0,0,0,2.54,22.1,280.7,280.7,0,0,1-203-101.3A95.69,95.69,0,0,0,36,130.4C36,164,53.53,193.7,80,211.1A97.5,97.5,0,0,1,35.22,199v1.2c0,47,34,86.1,79,95a100.76,100.76,0,0,1-25.94,3.4,94.38,94.38,0,0,1-18.51-1.8c12.51,38.5,48.92,66.5,92.05,67.3A199.59,199.59,0,0,1,39.5,405.6,203,203,0,0,1,16,404.2,278.68,278.68,0,0,0,166.74,448c181.36,0,280.44-147.7,280.44-275.8,0-4.2-.11-8.4-.31-12.5A198.48,198.48,0,0,0,496,109.5Z'/></svg></a>
                <a class="vk" href="#"><svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><path d='M484.7,132c3.56-11.28,0-19.48-15.75-19.48H416.58c-13.21,0-19.31,7.18-22.87,14.86,0,0-26.94,65.6-64.56,108.13-12.2,12.3-17.79,16.4-24.4,16.4-3.56,0-8.14-4.1-8.14-15.37V131.47c0-13.32-4.06-19.47-15.25-19.47H199c-8.14,0-13.22,6.15-13.22,12.3,0,12.81,18.81,15.89,20.84,51.76V254c0,16.91-3,20-9.66,20-17.79,0-61-66.11-86.92-141.44C105,117.64,99.88,112,86.66,112H33.79C18.54,112,16,119.17,16,126.86c0,13.84,17.79,83.53,82.86,175.77,43.21,63,104.72,96.86,160.13,96.86,33.56,0,37.62-7.69,37.62-20.5V331.33c0-15.37,3.05-17.93,13.73-17.93,7.62,0,21.35,4.09,52.36,34.33C398.28,383.6,404.38,400,424.21,400h52.36c15.25,0,22.37-7.69,18.3-22.55-4.57-14.86-21.86-36.38-44.23-62-12.2-14.34-30.5-30.23-36.09-37.92-7.62-10.25-5.59-14.35,0-23.57-.51,0,63.55-91.22,70.15-122' style='fill-rule:evenodd'/></svg></a>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</section>
<!-- end section -->

<!-- section -->
<div class="section section--last">
    <div class="container">
    <div class="row">
        <div class="col-12">
        <div class="partners owl-carousel">
            {% for book in last_book %}
                <a href="{{ book.get_absolute_url }}" class="partners__img">
                <img src="{{ book.image.url }}" alt="" height="200">
                </a>
            {% endfor %}
        </div>
        </div>
    </div>
    </div>
</div>
<!-- end section -->

{% endblock %}

config/home/templates/home/faq.html
{% extends '_base.html' %}
{% load static %}

{% block title_content %}
    مرکز راهنما
{% endblock %}

{% block content %}
    <!-- page title -->
    <section class="section section--first section--last section--head" data-bg="{% static 'img/bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section__wrap">
                        <!-- section title -->
                        <h2 class="section__title">مرکز راهنما</h2>
                        <!-- end section title -->

                        <!-- breadcrumb -->
                        <ul class="breadcrumb">
                            <li class="breadcrumb__item"><a href="{% url 'home:home' %}">خانه</a></li>
                            <li class="breadcrumb__item breadcrumb__item--active">مرکز راهنما</li>
                        </ul>
                        <!-- end breadcrumb -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end page title -->

    <!-- section -->
    <section class="section section--last section--catalog">
        <div class="container">

            <!-- content wrap -->
            <div class="col-12 col-lg-80">
                <div class="row">
                    <div class="col-12 col-lg-6">
                        <div class="faq">
                            <h3 class="faq__title">خانه</h3>
                            <ul class="faq__list">
                                <li><a href="{% url 'home:home' %}">صفحه‌ی اصلی (خانه)</a></li>
                                <li><a href="{% url 'home:faq' %}">مرکز راهنما</a></li>
                                <li><a href="{% url 'home:privacy' %}">حریم خصوصی</a></li>
                                <li><a href="{% url 'home:contact' %}">ارتباط با ما</a></li>
                                <li><a href="{% url 'home:about' %}">درباره‌ی ما</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-12 col-lg-6">
                        <div class="faq">
                            <h3 class="faq__title">پروفایل</h3>
                            <ul class="faq__list">
                                <li><a href="{% url 'accounts:user_register' %}">ساخت اکانت</a></li>
                                <li><a href="{% url 'order:premium_plans' %}">دریافت اشتراک پریمیوم</a></li>
                                <li><a href="{% url 'accounts:user_login' %}">لاگین</a></li>
                                <li><a href="{% url 'order:user_profile' %}">نمای پروفایل</a></li>
                                <li><a href="{% url 'accounts:user_info_edit' %}?next={{ request.path }}">تغییر اطلاعات</a></li>
                                <li><a href="{% url 'accounts:user_password_edit' %}?next={{ request.path }}">تغییر رمز عبور</a></li>
                                <li><a href="{% url 'accounts:user_logout' %}">خروج (logout)</a></li>
                                <li><a href="{% url 'accounts:forgot_password' %}">فراموشی رمز عبور</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-12 col-lg-6">
                        <div class="faq">
                            <h3 class="faq__title">کتاب</h3>
                            <ul class="faq__list">
                                <li><a href="{% url 'book:book_list' %}">لیست کتاب‌ها</a></li>
                                <li><a href="{% url 'accounts:user_favorites' %}">کتاب‌های موردعلاقه (نشان شده)</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-12 col-lg-6">
                        <div class="faq">
                            <h3 class="faq__title">وبلاگ</h3>
                            <ul class="faq__list">
                                <li><a href="{% url 'blog:blog_list' %}">لیست بلاگ‌ها</a></li>
                            </ul>
                        </div>
                    </div>

            <!-- end content wrap -->
        </div>
        <!-- end catalog -->
        </div>
    </section>
    <!-- end section -->

    <!-- section -->
    <div class="section section--last">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="partners owl-carousel">
                        {% for book in last_book %}
                            <a href="{{ book.get_absolute_url }}" class="partners__img">
                                <img src="{{ book.image.url }}" alt="" height="200">
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end section -->

{% endblock %}

config/home/templates/home/privacy.html
{% extends '_base.html' %}
{% load static %}

{% block title_content %}
    حریم خصوصی
{% endblock %}

{% block content %}
<!-- page title -->
<section class="section section--first section--last section--head" data-bg="{% static 'img/bg.jpg' %}">
    <div class="container">
    <div class="row">
        <div class="col-12">
        <div class="section__wrap">
            <!-- section title -->
            <h2 class="section__title">حریم خصوصی</h2>
            <!-- end section title -->

            <!-- breadcrumb -->
            <ul class="breadcrumb">
            <li class="breadcrumb__item"><a href="{% url 'home:home' %}">خانه</a></li>
            <li class="breadcrumb__item breadcrumb__item--active">حریم خصوصی</li>
            </ul>
            <!-- end breadcrumb -->
        </div>
        </div>
    </div>
    </div>
</section>
<!-- end page title -->

<!-- privacy -->
<section class="section">
    <div class="container">
    <div class="row">
        <!-- section text -->
        <div class="col-12">
        <p class="section__text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.</p>

        <p class="section__text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.</p>
        <p class="section__text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.</p>
        <p class="section__text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.</p>

        </div>
        <!-- end section text -->


    </div>
    </div>
</section>
<!-- end privacy -->

<!-- section -->
<div class="section section--last">
    <div class="container">
    <div class="row">
        <div class="col-12">
        <div class="partners owl-carousel">
            {% for book in last_book %}
                <a href="{{ book.get_absolute_url }}" class="partners__img">
                <img src="{{ book.image.url }}" alt="" height="200">
                </a>
            {% endfor %}
        </div>
        </div>
    </div>
    </div>
</div>
<!-- end section -->

{% endblock %}