config/accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

favorites_url = [
    path('', views.UserFavoritesView.as_view(), name='user_favorites'),
    path('add/<int:pk>/', views.AddFavoritesView.as_view(), name='add_favorites'),
    path('remove/<int:pk>/', views.RemoveFavoritesView.as_view(), name='remove_favorites')
]

profile_url = [
    path('info/', views.EditUserInfoView.as_view(), name='user_info_edit'),
    path('password/', views.UpdatePassword.as_view(), name='user_password_edit')
]

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('forgot/', views.UserPasswordResetView.as_view(), name='forgot_password'),
    path('forgot/verify/', views.UserPasswordResetVerifyCodeView.as_view(), name='forgot_password_verify'),

    path('edit/', include(profile_url)),
    path('favorites/', include(favorites_url)),
]

config/blog/urls.py
from django.urls import path

from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/<slug:slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('book/', include('book.urls', namespace='book')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('order/', include('order.urls', namespace='order'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/home/urls.py
from django.urls import path

from . import views


app_name = "home"
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('about/', views.about_view, name="about"),
    path('contact/', views.contacts_view, name="contact"),
    path('faq/', views.faq_view, name="faq"),
    path('privacy/', views.privacy_view, name="privacy"),
]

config/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from ckeditor.fields import RichTextField
from .managers import UserManager
import datetime


class User(AbstractBaseUser, PermissionsMixin):
    # user data
    email = models.EmailField(max_length=255, unique=True, null=True, blank=True)
    phone_number = models.CharField(max_length=11, unique=True)
    full_name = models.CharField(max_length=100)
    # user status
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    premium_expire_date = models.DateTimeField(blank=True, null=True)

    favorites = models.ManyToManyField('book.Book', related_name='favorites', blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email', 'full_name']

    def __str__(self):
        return "%s - %s" % (self.phone_number, self.full_name,)

    @property
    def is_staff(self):
        return self.is_admin

    @property
    def is_premium(self) -> bool:
        if not self.premium_expire_date:
            return False
        # return self.premium_expire_date >= datetime.datetime.now()
        return False


class OtpCode(models.Model):
    phone_number = models.CharField(max_length=11, unique=True)
    code = models.PositiveSmallIntegerField()
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.phone_number} - {self.code} - {self.created}'

config/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib import messages
from .models import OtpCode, User
from utils import send_otp_code
from django.views import View
from book.models import Book
import random

from . import forms


class UserRegisterView(View):
    form_class = forms.UserRegistrationForm
    template_name = 'accounts/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            print('valid')
            random_code = random.randint(1000, 9999)
            send_otp_code(form.cleaned_data['phone'], random_code)
            OtpCode.objects.create(phone_number=form.cleaned_data['phone'], code=random_code)
            request.session['user_registration_info'] = {
                'phone_number': form.cleaned_data['phone'],
                # 'email': form.cleaned_data['email'],
                'full_name': form.cleaned_data['full_name'],
                'password': form.cleaned_data['password1'],
            }
            messages.success(request, f"کد به {form.cleaned_data['phone']} ارسال شد", 'success')
            return redirect('accounts:verify_code')
        return render(request, self.template_name, {'form': form})


class UserRegisterVerifyCodeView(View):
    form_class = forms.VerifyCodeForm
    template_name = 'accounts/verify.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        user_session = request.session['user_registration_info']
        code_instance = OtpCode.objects.get(phone_number=user_session['phone_number'])
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['code'] == code_instance.code:
                User.objects.create_user(
                    user_session['phone_number'],
                    None,
                    # user_session['email'],
                    user_session['full_name'],
                    user_session['password']
                )

                code_instance.delete()
                messages.success(request, 'اکانت با موفقیت ساخته شد', 'success')
                return redirect('accounts:user_login')
            else:
                messages.error(request, 'کد اشتباه است', 'danger')
                return redirect('accounts:verify_code')
        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):

    def setup(self, request, *args, **kwargs):
        self.referring_page = request.GET.get('next', '/')
        return super().setup(request, *args, **kwargs)

    def get(self, request):
        logout(request)
        messages.success(request, 'با موفقیت خارج شدید', 'success')
        return redirect(self.referring_page)


class UserLoginView(View):
    form_class = forms.UserLoginForm
    template_name = 'accounts/login.html'

    def setup(self, request, *args, **kwargs):
        self.referring_page = request.GET.get('next', '/')
        return super().setup(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class
        # print('-' * 10, self.referring_page)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, phone_number=cd['phone'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'با موفقیت وارد شدید', 'info')
                return redirect(self.referring_page)
            messages.warning(request, 'شماره تلفن یا پسورد اشتباه است!', 'warning')
        return render(request, self.template_name, {'form': form})


class UserPasswordResetView(View):
    form_class = forms.UserPasswordResetForm
    template_name = 'accounts/password_reset_phone.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            random_code = random.randint(1000, 9999)
            send_otp_code(form.cleaned_data['phone'], random_code)
            OtpCode.objects.create(phone_number=form.cleaned_data['phone'], code=random_code)
            request.session['user_password_reset_info'] = {
                'phone_number': form.cleaned_data['phone']
            }
            messages.success(request, 'کد برای شما ارسال شد', 'success')
            return redirect('accounts:forgot_password_verify')
        return render(request, self.template_name, {'form': form})


class UserPasswordResetVerifyCodeView(View):
    form_class = forms.UserPasswordResetVerifyCodeForm
    template_name = 'accounts/password_reset_verify_code.html'

    def get(self, request):
        form = self.form_class
        user_session = request.session['user_password_reset_info']
        return render(request, self.template_name, {'form': form, 'phone_number': user_session['phone_number']})

    def post(self, request):
        user_session = request.session['user_password_reset_info']
        code_instance = OtpCode.objects.get(phone_number=user_session['phone_number'])
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['code'] == code_instance.code:
                user = User.objects.get(phone_number=user_session['phone_number'])
                user.set_password(cd['password2'])
                user.save()

                code_instance.delete()
                messages.success(request, 'پسورد شما با موفقیت تغییر کرد', 'success')
                return redirect('accounts:user_login')
            else:
                messages.error(request, 'کد وارد شده صحیح نمی‌باشد', 'danger')
                return redirect('accounts:forgot_password')
        return render(request, self.template_name, {'form': form})


class UserFavoritesView(LoginRequiredMixin, View):

    def get(self, request):
        favorites_list = self.request.user.favorites.all()
        # print(favorites_list)
        return render(request, 'accounts/favorites.html', {'favorites_list': favorites_list})


class AddFavoritesView(LoginRequiredMixin, View):

    def setup(self, request, *args, **kwargs):
        self.user_fav = request.user.favorites
        self.referring_page = request.GET.get('next', '/')

        return super().setup(request, *args, **kwargs)

    def get(self, request, pk):
        in_favorites_list = self.user_fav.filter(pk=pk).exists()
        if in_favorites_list:
            messages.error(request, 'کتاب قبلا به لیست اضافه شده است', 'danger')
            return redirect(self.referring_page)

        book = get_object_or_404(Book, pk=pk)
        self.user_fav.add(book)
        # self.user_fav.save()

        messages.success(request, 'کتاب با موفقیت به لیست اضافه شد', 'success')
        return redirect(self.referring_page)


class RemoveFavoritesView(LoginRequiredMixin, View):

    def setup(self, request, *args, **kwargs):
        self.user_fav = request.user.favorites
        self.referring_page = request.GET.get('next', '/')

        return super().setup(request, *args, **kwargs)

    def get(self, request, pk):
        in_favorites_list = self.user_fav.filter(pk=pk).exists()
        if not in_favorites_list:
            messages.error(request, 'کتاب در لیست نیست', 'danger')
            return redirect(self.referring_page)

        book = get_object_or_404(Book, pk=pk)
        self.user_fav.remove(book)
        # self.user_fav.save()

        messages.success(request, 'کتاب با موفقیت از لیست حذف شد', 'success')
        return redirect(self.referring_page)


class EditUserInfoView(LoginRequiredMixin, View):
    form_class = forms.EditUserInfoForm
    template_name = 'accounts/edit_info.html'

    def get(self, request):
        form = self.form_class(
            data={
                'phone': request.user.phone_number,
                'email': request.user.email,
                'full_name': request.user.full_name
            },
            request=request
        )
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, request=request)
        if form.is_valid():
            form.save(commit=True)

            messages.success(request, 'اطلاعات با موفقیت آپدیت شد', 'success')
            return redirect('accounts:user_info_edit')
        return render(request, self.template_name, {'form': form})


class UpdatePassword(PasswordChangeView):
    form_class = forms.CustomPasswordChangeForm
    success_url = '/'
    template_name = 'accounts/change_password.html'

    def form_valid(self, form):
        messages.success(request, 'پسورد با موفقیت آپدیت شد', 'success')
        return super().form_valid(form)

config/accounts/templates/accounts/_base.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl" lang="fa-IR">

<style>
    .loginfrm {
        color: white;
    }

    .custom-red-button {
        background-color: red;
        color: white; /* Set text color to contrast with the red background */
    }
</style>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS -->
    <link rel="stylesheet" href={% static "css/bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "css/owl.carousel.min.css" %}>
    <link rel="stylesheet" href={% static "css/magnific-popup.css" %}>
    <link rel="stylesheet" href={% static "css/nouislider.min.css" %}>
    <link rel="stylesheet" href={% static "css/jquery.mCustomScrollbar.min.css" %}>

    <link rel="stylesheet" href={% static "css/main.css" %}>

    <!-- Favicons -->
    <link rel="icon" type="image/png" sizes="32x32" href={% static "icon/favicon-32x32.png" %}>
    <link rel="apple-touch-icon" href={% static "icon/favicon-32x32.png" %}>

    <meta name="description" content="">
    <meta name="keywords" content="">

    <title>
        {% block title_content %}{% endblock %}
    </title>

</head>
<body>
<!-- sign in -->
<div class="sign section--full-bg" data-bg="{% static 'img/bg2.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="sign__content">
                    <!-- registration form -->
                    <div class="sign__form">
                        <a href="{% url 'home:home' %}" class="sign__logo">
                            <img src='{% static "img/j-logo.svg" %}' alt="">
                        </a>

                        {% if messages %}
                            {% for message in messages %}
                                <div class="container alert alert-{{ message.tags }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}

                        {% block content %}
                        {% endblock %}

                    </div>
                    <!-- registration form -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end sign in -->

<!-- JS -->
<script src={% static "js/jquery-3.5.0.min.js" %}></script>
<script src={% static "js/bootstrap.bundle.min.js" %}></script>
<script src={% static "js/owl.carousel.min.js" %}></script>
<script src={% static "js/jquery.magnific-popup.min.js" %}></script>
<script src={% static "js/wNumb.js" %}></script>
<script src={% static "js/nouislider.min.js" %}></script>
<script src={% static "js/jquery.mousewheel.min.js" %}></script>
<script src={% static "js/jquery.mCustomScrollbar.min.js" %}></script>
<script src={% static "js/main.js" %}></script>
</body>


</html>

config/accounts/templates/accounts/change_password.html
{% extends 'accounts/_base.html'%}

{% block title_content %}
    تغییر اظلاعات
{% endblock %}

{% block content %}

<form action="" method="post" class="loginfrm">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }}

            {{ field }}
            {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
    <input class="sign__btn" type="submit" value="ثبت تغییر">
</form>
<span class="sign__text">منصرف شدید ؟ <a href="{% url 'home:home' %}">بازگشت!</a>
</span>

{% endblock %}

config/accounts/templates/accounts/edit_info.html
{% extends 'accounts/_base.html'%}

{% block title_content %}
    تغییر اظلاعات
{% endblock %}

{% block content %}

<form action="" method="post" class="loginfrm">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }}

            {{ field }}
            {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
    <input class="sign__btn" type="submit" value="ثبت تغییر">
</form>
<span class="sign__text">رفتن به <a href="{% url 'accounts:user_password_edit' %}">صفحه تغییر پسورد</a> <br>
<span class="sign__text">منصرف شدید ؟ <a href="{% url 'home:home' %}">بازگشت!</a>
</span>

{% endblock %}

config/accounts/templates/accounts/favorites.html
{% extends '_base.html' %}
{% load static %}

{% block title_content %}
    نشان ها
{% endblock %}


{% block content %}

    <!-- page title -->
    <section class="section section--first section--last section--head" data-bg="{% static 'img/bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section__wrap">
                        <!-- section title -->
                        <h2 class="section__title">نشان ها</h2>
                        <!-- end section title -->

                        <!-- breadcrumb -->
                        <ul class="breadcrumb">
                            <li class="breadcrumb__item"><a href="{% url 'home:home' %}">خانه</a></li>
                            <li class="breadcrumb__item breadcrumb__item--active">نشان ها</li>
                        </ul>
                        <!-- end breadcrumb -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end page title -->


    <section class="section section--last section--catalog">
        <div class="container">
            <!-- catalog -->
            <div class="row catalog">
                <!-- filter wrap -->
                {#        {% include 'filter_wrap.html' %}#}
                <!-- end filter wrap -->

                <!-- content wrap -->
                <div class="col-12 col-lg-80">
                    <div class="row">
                        <!-- card -->
                        {% for fav in favorites_list %}
                            <div class="col-12 col-sm-6 col-md-4 col-xl-3">
                                <div class="card">
                                    <a href="{{ fav.get_absolute_url }}" class="card__cover">
                                        <img src="{{ fav.image.url }}" alt="" height="300">
                                    </a>

                                    {#                    <ul class="card__platforms">#}
                                    {#                    <li class="ps"><svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><path d='M399.77,203c-.8-17.1-3.3-34.5-10.8-50.1a82.45,82.45,0,0,0-16.5-23.2,105.59,105.59,0,0,0-21.3-16.3c-17.1-10.2-37.5-17-84.4-31S192,64,192,64V422.3l79.9,25.7s.1-198.8.1-299.5v-3.8c0-9.3,7.5-16.8,16.1-16.8h.5c8.5,0,15.5,7.5,15.5,16.8V278c11,5.3,29.2,9.3,41.8,9.1a47.79,47.79,0,0,0,24-5.7,49.11,49.11,0,0,0,18.4-17.8,78.64,78.64,0,0,0,9.9-27.3C400.07,225.5,400.17,214.2,399.77,203Z'/><path d='M86.67,357.8c27.4-9.8,89.3-29.5,89.3-29.5V281.1s-76.5,24.8-111.3,37.1c-8.6,3.1-17.3,5.9-25.7,9.5-9.8,4.1-19.4,8.7-28.1,14.8a26.29,26.29,0,0,0-9.2,10.1,17.36,17.36,0,0,0-.5,13.6c2,5.1,5.8,9.3,10.1,12.6,7.8,5.9,17.1,9.5,26.4,12.2a262.42,262.42,0,0,0,88.4,13.3c14.5-.2,36-1.9,50-4.4v-42s-11,2.5-41.3,12.5c-4.6,1.5-9.2,3.3-14,4.3a104.87,104.87,0,0,1-21.6,2.2c-6.5-.3-13.2-.7-19.3-3.1-2.2-1-4.6-2.2-5.5-4.6-.8-2,.3-4,1.7-5.4C78.87,360.9,82.87,359.3,86.67,357.8Z'/><path d='M512,345.9c-.1-6-3.7-11.2-7.9-15-7.1-6.3-15.9-10.3-24.7-13.5-5.5-1.9-9.3-3.3-14.7-5-25.2-8.2-51.9-11.2-78.3-11.3-8,.3-23.1.5-31,1.4-21.9,2.5-67.3,15.4-67.3,15.4v48.8s67.5-21.6,96.5-31.8a94.43,94.43,0,0,1,30.3-4.6c6.5.2,13.2.7,19.4,3.1,2.2.9,4.5,2.2,5.5,4.5.9,2.6-.9,5-2.9,6.5-4.7,3.8-10.7,5.3-16.2,7.4-41,14.5-132.7,44.7-132.7,44.7v47s117.2-39.6,170.8-58.8c8.9-3.3,17.9-6.1,26.4-10.4,7.9-4,15.8-8.6,21.8-15.3A19.74,19.74,0,0,0,512,345.9Z'/></svg></li>#}
                                    {#                    <li class="xb"><svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><path d='M126.8,248.3c39.7-58.6,77.9-92.8,77.9-92.8s-42.1-48.9-92.8-67.4l-3.3-.8A224.13,224.13,0,0,0,77.2,391C77.2,386.6,77.8,320.7,126.8,248.3Z'/><path d='M480,256A223.71,223.71,0,0,0,403.4,87.3l-3.2.9c-50.7,18.5-92.9,67.4-92.9,67.4s38.2,34.2,77.9,92.8c49,72.4,49.6,138.3,49.5,142.7A222.8,222.8,0,0,0,480,256Z'/><path d='M201.2,80.9c29.3,13.1,54.6,34.6,54.6,34.6s25.5-21.4,54.8-34.6c36.8-16.5,64.9-11.3,72.3-9.5a224.06,224.06,0,0,0-253.8,0C136.3,69.6,164.3,64.3,201.2,80.9Z'/><path d='M358.7,292.9C312.4,236,255.8,199,255.8,199s-56.3,37-102.7,93.9c-39.8,48.9-54.6,84.8-62.6,107.8l-1.3,4.8a224,224,0,0,0,333.6,0l-1.4-4.8C413.4,377.7,398.5,341.8,358.7,292.9Z'/></svg></li>#}
                                    {#                    <li class="wn"><svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><path d='M480,265H232V444l248,36V265Z'/><path d='M216,265H32V415l184,26.7V265Z'/><path d='M480,32,232,67.4V249H480V32Z'/><path d='M216,69.7,32,96V249H216V69.7Z'/></svg></li>#}
                                    {#                    <li class="ap"><svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><path d='M349.13,136.86c-40.32,0-57.36,19.24-85.44,19.24C234.9,156.1,212.94,137,178,137c-34.2,0-70.67,20.88-93.83,56.45-32.52,50.16-27,144.63,25.67,225.11,18.84,28.81,44,61.12,77,61.47h.6c28.68,0,37.2-18.78,76.67-19h.6c38.88,0,46.68,18.89,75.24,18.89h.6c33-.35,59.51-36.15,78.35-64.85,13.56-20.64,18.6-31,29-54.35-76.19-28.92-88.43-136.93-13.08-178.34-23-28.8-55.32-45.48-85.79-45.48Z'/><path d='M340.25,32c-24,1.63-52,16.91-68.4,36.86-14.88,18.08-27.12,44.9-22.32,70.91h1.92c25.56,0,51.72-15.39,67-35.11C333.17,85.89,344.33,59.29,340.25,32Z'/></svg></li>#}
                                    {#                    </ul>#}

                                    <div class="card__title">
                                        <h3 dir="auto"><a href="{{ fav.get_absolute_url }}">{{ fav.title }}</a></h3>
                                    </div>

                                    <div class="card__actions">
                                        <a class="card__buy" type="button" href="{{ fav.get_absolute_url }}">مشاهده</a>

                                        <a class="card__favorite card__favorite--delete" type="button"
                                           href="{% url 'accounts:remove_favorites' fav.pk %}?next={{ request.path }}">
                                            <svg xmlns='http://www.w3.org/2000/svg' width='512' height='512'
                                                 viewBox='0 0 512 512'>
                                                <path d='M112,112l20,320c.95,18.49,14.4,32,32,32H348c17.67,0,30.87-13.51,32-32l20-320'
                                                      style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/>
                                                <line x1='80' y1='112' x2='432' y2='112'
                                                      style='stroke-linecap:round;stroke-miterlimit:10;stroke-width:32px'/>
                                                <path d='M192,112V72h0a23.93,23.93,0,0,1,24-24h80a23.93,23.93,0,0,1,24,24h0v40'
                                                      style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/>
                                                <line x1='256' y1='176' x2='256' y2='400'
                                                      style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/>
                                                <line x1='184' y1='176' x2='192' y2='400'
                                                      style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/>
                                                <line x1='328' y1='176' x2='320' y2='400'
                                                      style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/>
                                            </svg>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <!-- end card -->
                    </div>
                </div>
                <!-- end content wrap -->
            </div>
            <!-- end catalog -->
        </div>
    </section>


{% endblock %}

config/accounts/templates/accounts/login.html
{% extends 'accounts/_base.html'%}

{% block title_content %}
    لاگین
{% endblock %}

{% block content %}
<form action="" method="post" class="loginfrm">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }}

            {{ field }}
            {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
    <input class="sign__btn" type="submit" value="ورود">
</form>

<span class="sign__text">حساب کاربری ندارید ؟ <a href="{% url 'accounts:user_register' %}">ثبت نام</a></span>

<span class="sign__text"><a href="{% url 'accounts:forgot_password' %}">رمز عبور خود را فراموش کردید ؟</a></span>
{% endblock %}

config/accounts/templates/accounts/password_reset_phone.html
{% extends 'accounts/_base.html'%}

{% block title_content %}
    فراموشی رمز عبور
{% endblock %}

{% block content %}

<form action="" method="post" class="loginfrm">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }}

            {{ field }}
            {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
    <input class="sign__btn" type="submit" value="ارسال کد">
</form>

<span class="sign__text">حساب کاربری ندارید ؟ <a href="{% url 'accounts:user_register' %}">ثبت نام</a></span>

{% endblock %}

config/accounts/templates/accounts/verify.html
{% extends 'accounts/_base.html'%}

{% block title_content %}
    کتاب‌ها
{% endblock %}

{% block content %}

<form action="" method="post" class="loginfrm">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }}

            {{ field }}
            {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
    <input class="sign__btn" type="submit" value="ثبت نام">
</form>
<span class="sign__text"><a href="{% url 'accounts:user_register' %}">اصلاح شماره!</a>
</span>

{% endblock %}