config/accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

favorites_url = [
    path('', views.UserFavoritesView.as_view(), name='user_favorites'),
    path('add/<int:pk>/', views.AddFavoritesView.as_view(), name='add_favorites'),
    path('remove/<int:pk>/', views.RemoveFavoritesView.as_view(), name='remove_favorites')
]

profile_url = [
    path('info/', views.EditUserInfoView.as_view(), name='user_info_edit'),
    path('password/', views.UpdatePassword.as_view(), name='user_password_edit')
]

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('forgot/', views.UserPasswordResetView.as_view(), name='forgot_password'),
    path('forgot/verify/', views.UserPasswordResetVerifyCodeView.as_view(), name='forgot_password_verify'),

    path('edit/', include(profile_url)),
    path('favorites/', include(favorites_url)),
]

config/blog/urls.py
from django.urls import path

from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/<slug:slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
]

config/book/urls.py
from django.urls import path, include
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.BookListView.as_view(), name="book_list"),
    path('book/<int:pk>/<slug:slug>/', views.BookDetailView.as_view(), name="book_detail")
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('book/', include('book.urls', namespace='book')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('order/', include('order.urls', namespace='order'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/home/urls.py
from django.urls import path

from . import views


app_name = "home"
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('about/', views.about_view, name="about"),
    path('contact/', views.contacts_view, name="contact"),
    path('faq/', views.faq_view, name="faq"),
    path('privacy/', views.privacy_view, name="privacy"),
]

config/templates/_base.html
{% load static %}

<!DOCTYPE html>
<html dir="rtl" lang="fa-IR">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/nouislider.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">


    <!-- Favicons -->
    <link rel="icon" type="image/png" href="{% static 'icon/favicon-32x32.png' %}" sizes="32x32">
    <link rel="apple-touch-icon" href="{% static 'icon/favicon-32x32.png' %}">

    <meta name="description" content="">
    <meta name="keywords" content="">

    <title>
        بیتوته کتاب -
        {% block title_content %}
        {% endblock %}
    </title>

    {% block style_content %} {% endblock %}
    <style>
        /* CSS for header__notifications container */
        .header__notifications {
            position: relative;
            top: 10px;
            right: 10px;
        }

        /* CSS for header__message */
        .header__message {
            padding: 10px;
            margin-bottom: 10px;
            background-color: #f0f0f0;
            border: 1px solid #ddd;
            border-radius: 5px;
            font-size: 14px;
            position: relative;
            overflow: hidden; /* Prevents button from overlapping text */
        }

        .header__message span {
            margin-right: 10px;
        }

        .header__message {
            display: flex; /* Use flexbox to align text and button horizontally */
            align-items: center; /* Center items vertically */
            padding: 10px;
            margin-bottom: 10px;
            background-color: #f0f0f0;
            border: 1px solid #ddd;
            border-radius: 5px;
            font-size: 14px;
            position: relative;
        }

        .header__message span {
            flex-grow: 1; /* Allow the text to grow and take up available space */
        }

        .header__message button.header__message-remove {
            background-color: #ff0000;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            padding: 5px 10px;
        }


        /* Optionally, you can style different message types (e.g., success, error) differently */
        .header__message.alert-success {
            background-color: #dff0d8;
            color: #3c763d;
        }

        .header__message.alert-error {
            background-color: #f2dede;
            color: #a94442;
        }

    </style>

</head>
<body>
<!-- header -->
{% include 'inc/navbar.html' %}
<!-- end header -->


{% block content %}
{% endblock %}

<!-- footer -->
{% include 'inc/footer.html' %}
<!-- end footer -->

<!-- JS -->
<script src="{% static 'js/jquery-3.5.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/wNumb.js' %}"></script>
<script src="{% static 'js/nouislider.min.js' %}"></script>
<script src="{% static 'js/jquery.mousewheel.min.js' %}"></script>
<script src="{% static 'js/jquery.mCustomScrollbar.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>


</html>

config/templates/navbar.html
{% load static %}

<header class="header">
    <div class="header__wrap">
    <div class="container">
        <div class="row">
        <div class="col-12">
            <div class="header__content">
            <button class="header__menu" type="button">
                <span></span>
                <span></span>
                <span></span>
            </button>

            <a href="{% url 'book:home' %}" class="header__logo">
                <img src="{% static 'img/logo.svg' %}" alt="">
            </a>

            <ul class="header__nav">
                <li class="header__nav-item">
                <a class="header__nav-link" href="{% url 'book:home' %}">خانه</a>
                </li>
                <li class="header__nav-item">
                <a class="header__nav-link" href="#" role="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">کتاب ها</a>

                <ul class="dropdown-menu header__nav-menu" aria-labelledby="dropdownMenu1">
                    <li><a href="{% url 'book:book_list' %}">همه‌ی کتاب‌ها</a></li>
                    <li><a href="{% url 'accounts:user_favorites' %}">کتاب‌های نشان شده</a></li>
                </ul>
                </li>
                <li class="header__nav-item">
                <a class="header__nav-link" href="#" role="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">بلاگ</a>

                <ul class="dropdown-menu header__nav-menu" aria-labelledby="dropdownMenu2">
                    <li><a href="news.html">اخبار</a></li>
                    <li><a href="article.html">مقالات</a></li>
                    <li><a href="interview.html">مصاحبه ها</a></li>
                </ul>
                </li>
                <li class="header__nav-item">
                <a class="header__nav-link" href="faq.html">مرکز راهنما</a>
                </li>
                <li class="header__nav-item">
                <a class="header__nav-link" href="#" role="button" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><circle cx='256' cy='256' r='32' style='fill:none; stroke-miterlimit:10;stroke-width:32px'/><circle cx='416' cy='256' r='32' style='fill:none;stroke-miterlimit:10;stroke-width:32px'/><circle cx='96' cy='256' r='32' style='fill:none;stroke-miterlimit:10;stroke-width:32px'/></svg>
                </a>

                <ul class="dropdown-menu header__nav-menu header__nav-menu--scroll" aria-labelledby="dropdownMenu3">
                    <li><a href="checkout.html">ثبت نهایی</a></li>
                    <li><a href="{% url 'accounts:user_favorites' %}">نشان ها</a></li>
                    <li><a href="about.html">درباره ما</a></li>
                    <li><a href="profile.html">پروفایل</a></li>
                    <li><a href="signin.html">ورود اعضا</a></li>
                    <li><a href="signup.html">ثبت نام</a></li>
                    <li><a href="forgot.html">فراموشی رمز عبور</a></li>
                    <li><a href="privacy.html">حریم خصوصی</a></li>
                    <li><a href="contacts.html">تماس با ما</a></li>
                    <li><a href="404.html">صفحه 404</a></li>
                </ul>
                </li>
            </ul>

            {% if user.is_authenticated %}
                <div class="header__actions">
                    <a href="{% url 'accounts:user_logout' %}" class="header__login mr-auto">
                    <svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'>
                        <path d='M192,176V136a40,40,0,0,1,40-40H392a40,40,0,0,1,40,40V376a40,40,0,0,1-40,40H240c-22.09,0-48-17.91-48-40V336' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/>
                        <polyline points='288 336 368 256 288 176' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/>
                        <line x1='80' y1='256' x2='352' y2='256' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/>
                    </svg>
                    <span>خروج</span>
                    </a>
                </div>
            {% else %}
                <div class="header__actions">
                    <a href="{% url 'accounts:user_login' %}" class="header__login mr-auto">
                    <svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'>
                        <path d='M192,176V136a40,40,0,0,1,40-40H392a40,40,0,0,1,40,40V376a40,40,0,0,1-40,40H240c-22.09,0-48-17.91-48-40V336' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/>
                        <polyline points='288 336 368 256 288 176' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/>
                        <line x1='80' y1='256' x2='352' y2='256' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/>
                    </svg>
                    <span>ورود / ثبت‌نام</span>
                    </a>
                </div>
            {% endif %}
            </div>
        </div>
        </div>
    </div>
    </div>

    <div class="header__wrap">
    <div class="container">
        <div class="row">
        <div class="col-12">
            <div class="header__content">
            <form action="catalog.html" class="header__form" method="GET">
                <input type="text" class="header__input" placeholder="جستجو کنید ...">
                <select class="header__select">
                <option value="0">تمام ژانر ها</option>
                <option value="1">اکشن</option>
                <option value="3">ماجرا جویی</option>
                <option value="4">ترسناک</option>
                <option value="5">ورزشی</option>
                <option value="6">جنگی</option>
                <option value="7">مهیج</option>
                </select>
                <button class="header__btn" type="button">
                <svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><path d='M221.09,64A157.09,157.09,0,1,0,378.18,221.09,157.1,157.1,0,0,0,221.09,64Z' style='fill:none;stroke-miterlimit:10;stroke-width:32px'/><line x1='338.29' y1='338.29' x2='448' y2='448' style='fill:none;stroke-linecap:round;stroke-miterlimit:10;stroke-width:32px'/></svg>
                </button>
            </form>

            {% if messages %}
                {% for message in messages %}
                    <div class="cke_notifications_area alert alert-{{ message.tags }} ">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="header__actions header__actions--2">
                <a href="{% url 'accounts:user_favorites' %}" class="header__link">
                <svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><path d='M352.92,80C288,80,256,144,256,144s-32-64-96.92-64C106.32,80,64.54,124.14,64,176.81c-1.1,109.33,86.73,187.08,183,252.42a16,16,0,0,0,18,0c96.26-65.34,184.09-143.09,183-252.42C447.46,124.14,405.68,80,352.92,80Z' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/></svg>
                <span>نشان ها</span>
                </a>

                <a href="checkout.html" class="header__link">
                <svg xmlns='http://www.w3.org/2000/svg' width='512' height='512' viewBox='0 0 512 512'><circle cx='176' cy='416' r='16' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/><circle cx='400' cy='416' r='16' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/><polyline points='48 80 112 80 160 352 416 352' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/><path d='M160,288H409.44a8,8,0,0,0,7.85-6.43l28.8-144a8,8,0,0,0-7.85-9.57H128' style='fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px'/></svg>
                <span>2200 تومان</span>
                </a>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</header>